{
 "title": "Kubernetes Deployment Statefulset Daemonset metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(deployment)" },
   { "name": "Statefulset", "query": "label_values(statefulset)" },
   { "name": "Daemonset", "query": "label_values(daemonset)" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"nginx.*\"}) / sum (machine_memory_bytes{node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"nginx.*\"}[2m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{pod=~\"nginx.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_capacity{ job=\"kube-state-metrics\", node=\"docker-desktop\", resource=\"memory\", unit=\"byte\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=~\"^$\",pod=~\"nginx.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"nginx.*\"}[1m])) by (pod)",
     "legendFormat": " {{ pod }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"nginx.*\"}) by (pod,node)",
     "legendFormat": " {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod=~\"^nginx.*\"}) by (pod)",
     "legendFormat": " {{ pod }}"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"})) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kube_summary_pod_ephemeral_storage_used_bytes{pod=~\"nginx.*\"} / kube_node_status_capacity{resource=\"ephemeral_storage\"}) or vector(0)",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace((sum(rate(container_network_receive_bytes_total{id!=\"/\",pod=~\"nginx.*\"}[1m])) by (pod)), \"pod\", \"inbound_$1\", \"pod\", \"(.*)\")",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "label_replace(- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"nginx.*\"}[1m])) by (pod), \"pod\", \"nbound_$1\", \"pod\", \"(.*)\")",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}